Table si {
    fiscal_yr fy [ref: > fy_list.fiscal_yr]
    org_id varchar
    service_id varchar [ref: > service_id_list.service_id]
    fy_org_id_service_id varchar [pk]
    service_name_en varchar
    service_name_fr varchar
    service_description_en varchar
    service_description_fr varchar
    service_type varchar
    service_recipient_type varchar
    service_scope varchar
    client_target_groups varchar
    program_name_en varchar
    program_name_fr varchar
    client_feedback_channel varchar
    service_fee varchar
    last_GBA varchar
    ident_platform varchar
    ident_platform_comments varchar
    os_account_registration varchar
    os_authentication varchar
    os_application varchar
    os_decision varchar
    os_issuance varchar
    os_issue_resolution_feedback varchar
    os_comments_client_interaction_en varchar
    os_comments_client_interaction_fr varchar
    how_has_the_service_been_assessed_for_accessibility varchar
    last_service_review varchar
    last_service_improvement varchar
    sin_usage varchar
    cra_bn_identifier_usage varchar
    num_phone_enquiries varchar
    num_applications_by_phone varchar
    num_website_visits varchar
    num_applications_online varchar
    num_applications_in_person varchar
    num_applications_by_mail varchar
    num_applications_by_email varchar
    num_applications_by_fax varchar
    num_applications_by_other varchar
    special_remarks_en varchar
    special_remarks_fr varchar
    service_uri_en varchar
    service_uri_fr varchar
    num_applications_total varchar
    department_en varchar
    department_fr varchar
    program_id varchar
    automated_decision_system varchar
    automated_decision_system_description_en varchar
    automated_decision_system_description_fr varchar
    org_name_variant varchar
}

Table ss {
    fy_org_id_service_id varchar [ref: > si.fy_org_id_service_id]
    fy_org_id_service_id_service_standard_id varchar [pk]
    fiscal_yr fy
    service_id varchar
    service_name_en varchar
    service_name_fr varchar
    service_standard_id varchar
    service_standard_en varchar
    service_standard_fr varchar
    type varchar
    gcss_tool_fiscal_yr varchar
    channel varchar
    channel_comments_en varchar
    channel_comments_fr varchar
    target_type varchar
    target double
    volume_meeting_target int
    total_volume int
    performance double
    comments_en varchar
    comments_fr varchar
    target_met varchar
    standards_targets_uri_en varchar
    standards_targets_uri_fr varchar
    performance_results_uri_en varchar
    performance_results_uri_fr varchar
    org_id varchar
    department_en varchar
    department_fr varchar
    org_name_variant varchar
}

Table service_fte_spending {
    fy_org_id_service_id varchar [ref: > si.fy_org_id_service_id]
    service_id varchar
    fiscal_yr fy
    program_id varchar
    org_id varchar
    report_yr varchar
    measure_yr varchar
    planned_actual varchar
    ftes int
    spending double

    indexes {
      (fiscal_yr, org_id, service_id, program_id) [pk] 
    }
}

Table si_vol {
    fy_org_id_service_id varchar [ref: > si.fy_org_id_service_id]
    fiscal_yr fy
    org_id varchar
    service_id varchar
    channel varchar
    volume int
}

Table fy_list {
    fiscal_yr fy
}

enum fy {
    "2018-2019"
    "2019-2020"
    "2020-2021"
    "2021-2022"
    "2022-2023"
    "2023-2024"
    "2024-2025"
}

Table dept {
    org_id varchar [pk]
    department_en varchar
    department_fr varchar
}

Table service_id_list {
    service_id varchar [pk]
    org_id varchar [ref: > dept.org_id]
    service_name_en varchar
    service_name_fr varchar
    department_en varchar
    department_fr varchar
    fiscal_yr_first varchar
    fiscal_yr_latest varchar
    service_id_name_en varchar
    service_id_name_fr varchar
    service_scope_ext_or_ent varchar
}

Table maf_all {
    fiscal_yr fy [ref: > fy_list.fiscal_yr]
    org_id varchar [ref: > dept.org_id]
    department_en varchar
    department_fr varchar
    service_with_std_count int
    service_count_maf1 int
    maf1_score double
    service_standard_met int
    service_standard_count int
    maf2_score double
    online_e2e_count int
    service_count_maf5 int
    maf5_score double
    activated_point_count int
    point_count int
    maf6_score double
    improved_services_count int
    service_count_maf8 int
    maf8_score int

    indexes {
      (fiscal_yr, org_id) [pk] 
    }
}

Table drr_all {
    fiscal_yr fy [ref: - fy_list.fiscal_yr]
    hv_online_e2e_count int
    hv_service_count int
    dr2467_score double
    hvte_services_count_meeting_standard int
    hvte_services_count int
    dr2468_score double
    hv_online_applications int
    hv_total_applications int
    dr2469_score double
}