#!/bin/bash
#produces file paths of things safe to delete
find . -type d -name "__pycache__"
find outputs -type f -name "*.csv" 
find inputs -type f \( -iname "*.csv" -o -iname "*.json" \) ! -path "*/snapshots/*"