name: Generate Files

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  flatten-generated-files:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
	    uses: actions/setup-python@v4
	    with:
	      python-version: '3.10'

      # Ensure you're on the `master` branch
      - name: Switch to master branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin master
          git checkout master

      # Run the main.py script
      - name: Run the main.py script
        run: |
          python main.py

      # Add workflow directory to gitignore
      - name: Add workflows to gitignore
        run: |
          echo .github/ >> .gitignore

      # Flatten structure: Copy CSV files to root, remove everything else
      - name: Flatten structure
        run: |
          mkdir temp_csv  # Temporary directory for CSVs
          find . -type f -name '*.csv' -exec mv {} temp_csv/ \;  # Move all CSVs to temp
          find . -mindepth 1 \( -path './temp_csv*' -o -path './README.md' -o -path './.*' -prune \) -o -exec rm -rf {} + # Delete everything else
          mv temp_csv/* .  # Move CSVs back to root
          rmdir temp_csv  # Remove temporary directory

      # Commit and push changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update csv outputs by github action"
          git push --force origin generated-files

