name: Process and Release Service Data

on:
  push:
    branches:
      - master  # Run on all pushes to master
  pull_request:
    branches:
      - master  # Run on all PRs targeting master
  schedule:
    - cron: '0 0 * * 1-5'  # daily runs monday to friday
  workflow_dispatch:  # Allow manual triggers

jobs:
  generate-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements for python
        run: pip install -r requirements.txt

      - name: Get current date and commit hash
        id: metadata
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "time=$(date +'%H:%M')" >> $GITHUB_OUTPUT

      - name: Run main.py for live data
        run: python main.py

      - name: Prepare live files for release
        id: prepare_live_files
        run: |
          mkdir -p live_data_release
          echo "Copying live data files (.csv and .log)..."
          find outputs inputs -type f \( -name "*.csv" -o -name "*.log" \) \
            ! -path "*/snapshots/*" -size +0c \
            -exec cp {} live_data_release/ \; -exec echo "Copied: {}" \;
          
          echo "live_data_dir=live_data_release" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: service_data-${{ steps.metadata.outputs.commit_hash }}
          name: Service Data - ${{ steps.metadata.outputs.date }}
          body: |
            Automated service data release for ${{ steps.metadata.outputs.date }}
              - Generated on: ${{ steps.metadata.outputs.date }} at ${{ steps.metadata.outputs.time }} EST
              - Git Commit: ${{ steps.metadata.outputs.commit_hash }}
            Contains:
              - Live data CSVs 
          files: |
            live_data_release/**
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Cleanup
      - name: Cleanup
        run: rm -rf outputs inputs snapshots_release live_data_release

