name: Flatten Generated Files

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  flatten-generated-files:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure you're on the `generated-files` branch
      - name: Switch to generated-files branch
        run: |
          git fetch origin generated-files
          git checkout generated-files

      # Flatten structure: Copy CSV files to root, remove everything else
      - name: Flatten structure
        run: |
          mkdir temp_csv  # Temporary directory for CSVs
          find . -type f -name '*.csv' -exec mv {} temp_csv/ \;  # Move all CSVs to temp
          find . -mindepth 1 -delete  # Delete everything else
          mv temp_csv/* .  # Move CSVs back to root
          rmdir temp_csv  # Remove temporary directory

      # Commit and push changes
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Flatten structure: CSV files only"
          git push origin generated-files --force

