name: Generate CSV Files

on:
  push:
    branches:
      - master  # Run on all pushes to master
  pull_request:
    branches:
      - master  # Run on all PRs targeting master
  schedule:
    - cron: '0 0 * * *'  # Also keep daily runs at midnight
  workflow_dispatch:  # Allow manual triggers

jobs:
  generate-files:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements for python
        run: pip install -r requirements.txt

      # Ensure we have latest master
      - name: Get latest master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git fetch origin master
          git checkout master
          git pull origin master

      # Run the main.py script
      - name: Run the main.py script
        run: python main.py

      # Get current date and time for release tag
      - name: Get current date and time
        id: datetime
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "time=$(date +'%H-%M-%S')" >> $GITHUB_OUTPUT
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Create GitHub release with SQLite database
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: service_data-${{ steps.datetime.outputs.date }}-${{ steps.datetime.outputs.time }}
          name: Service Data Release ${{ steps.datetime.outputs.date }}
          body: |
            Automated service data release for ${{ steps.datetime.outputs.date }}
            
            Release Information:
            - Generated on: ${{ steps.datetime.outputs.date }} at ${{ steps.datetime.outputs.time }} UTC
            - Git Commit: ${{ steps.datetime.outputs.commit_hash }}
            
            This release contains:
            - SQLite database with all processed data
            - Database tables are prefixed with their source directory
          files: outputs/service_data.db
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Delete workflow directory from repo
      - name: Delete workflow directory
        run: rm -rf .github/ .gitignore

      # Flatten structure: Copy CSV files to root, remove everything else
      - name: Flatten structure
        run: |
          mkdir temp_files  # Temporary directory for files
          find . -type f -name '*.csv' -exec mv {} temp_files/ \;  # Move all CSVs to temp
          find . -mindepth 1 \( -path './temp_files*' -o -path './README.md' -o -path './.*' -prune \) -o -exec rm -rf {} + # Delete everything else
          mv temp_files/* .  # Move files back to root
          rmdir temp_files  # Remove temporary directory

      # Commit and push changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -B generated-files
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update csv outputs by github action"
          git push --force origin generated-files
