name: Process and Release Service Data

on:
  push:
    branches:
      - master  # Run on all pushes to master
  pull_request:
    branches:
      - master  # Run on all PRs targeting master
  schedule:
    - cron: '0 0 * * *'  # Also keep daily runs at midnight
  workflow_dispatch:  # Allow manual triggers

jobs:
  generate-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements for python
        run: pip install -r requirements.txt

      - name: Run main py script
        run: python main.py
        
      - name: Install pandas for SQLite database creation
        run: pip install pandas

      - name: Create SQLite database
        run: python src/create_sqlite.py

      - name: Get current date and commit hash
        id: metadata
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "time=$(date +'%H:%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: service_data-${{ steps.metadata.outputs.commit_hash }}
          name: Service Data - ${{ steps.metadata.outputs.date }} (${{ steps.metadata.outputs.commit_hash }})
          body: |
            Automated service data release for ${{ steps.metadata.outputs.date }}
                - Generated on: ${{ steps.metadata.outputs.date }} at ${{ steps.metadata.outputs.time }} EST
                - Git Commit: ${{ steps.metadata.outputs.commit_hash }}
            Contains SQLite database with all processed data
          files: |
            outputs/service_data.sqlite
            outputs/**/*.csv
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Cleanup
      - name: Cleanup
        run: rm -rf outputs
