---
name: Run Jupyter Notebook
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 1
jobs:
  execute-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: List directory contents
        run: ls -R
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas nbconvert
      - name: Run Jupyter Notebook
        run: >
          jupyter nbconvert --to notebook --execute gc-service-data-script.ipynb \
            --output gc-service-data-script-output.ipynb
          mv *.csv output/
      - name: Configure Git for Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git fetch origin
          git checkout -B generated-files
          git add output/*.csv
          git commit -m "Update CSV outputs from Jupyter notebook"
          git push origin generated-files
      - name: Clean up old csv files
        run: |
          git fetch origin generated-files
          git checkout generated-files
          find output/ -type f -mtime +30 -delete
          git add output/
          git commit -m "Cleanup old files"
          git push origin generated-files

