---
name: Run Jupyter Notebook
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas nbconvert

      - name: List directory contents
        run: ls -R

      - name: Run Jupyter Notebook 
        run: >
          jupyter nbconvert --to notebook --execute --inplace gc-service-data-script.ipynb

      - name: List directory contents
        run: ls -R

      - name: Configure Git for Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push Changes to Generated Files Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git checkout -B generated-files
          git add *.csv
          git commit -m "Update CSV outputs from Jupyter notebook"
          git push --force origin generated-files

