---
name: Run Jupyter Notebook
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          pwd
          ls -al
          cd ..
          ls -al
          cd ..
          ls -al
          cd /
          ls -al

