---
name: Run Jupyter Notebook
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check directory
        run: |
          ls -al

      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: List directory contents
        run: |
          ls -al
          cd ..
          ls -al
