name: Run Jupyter Notebook

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight (UTC)

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: list directory contents
      - name: List directory contents
        run: ls -R

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas nbconvert

      # Step 5: Execute Jupyter Notebook
      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute gc-service-data-script.ipynb \
            --output gc-service-data-script-output.ipynb
          mv *.csv output/

      # Step 6: Commit and push the results
      - name: Commit and Push Outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.csv
          git commit -m "Update CSV outputs from Jupyter notebook"
          git push
